services:
  - type: web
    name: payverify-nepal
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract