services:
  - type: web
    name: payverify-nepal
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract